monolog:
    channels: ['db']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404]
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        db:
            channels: ['db']
            type: service
            id: Bolt\Log\LogHandler
