name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: Coding Standard
                        # tip: add "--ansi" to commands in CI to make them full of colors
                        run: vendor/bin/ecs check src --ansi

                    -
                        name: PHPStan
                        run: vendor/bin/phpstan analyse

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    # test the lowest version, to make sure checks pass on it
                    php-version: 7.2
                    coverage: none

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}
